"""Entry point for the stack subcommand."""

from pathlib import Path

import yaml

from tf2crossplane.logger import LOGGER
from tf2crossplane.settings import ResourceDef, StackSettings, WireDef
from tf2crossplane.stack.composition import generate_stack_composition
from tf2crossplane.stack.reader import load_xrd
from tf2crossplane.stack.xrd import generate_stack_xrd


def _parse_resource_flag(raw: str) -> ResourceDef:
    """Parse 'name:xrd-plural' CLI flag into a ResourceDef."""
    parts = raw.split(":", 1)
    if len(parts) != 2:
        raise ValueError(
            f"Invalid --resource format '{raw}'. Expected 'name:xrd-plural' "
            "(e.g. 'kms:xkmskeys')."
        )
    return ResourceDef(name=parts[0].strip(), xrd=parts[1].strip())


def _parse_wire_flag(raw: str) -> WireDef:
    """Parse 'source.outputs.field -> target.field' CLI flag into a WireDef."""
    if "->" not in raw:
        raise ValueError(
            f"Invalid --wire format '{raw}'. "
            "Expected 'source.outputs.field -> target.field' "
            "(e.g. 'kms.outputs.key_id -> ec2.kms_key_id')."
        )
    left, right = raw.split("->", 1)
    return WireDef(source=left.strip(), target=right.strip())


def _settings_from_file(stack_file: Path) -> StackSettings:
    """Load StackSettings from a *.stack.yaml definition file.

    Relative paths for xrd_dir and output_dir are resolved relative to the
    directory containing the stack file, not the current working directory.
    """
    stack_file = stack_file.resolve()
    base_dir = stack_file.parent

    with open(stack_file) as f:
        data = yaml.safe_load(f)

    resources = [ResourceDef(**r) for r in data.get("resources", [])]
    wires = [WireDef(**w) for w in data.get("wires", [])]

    def _resolve(raw: str) -> Path:
        p = Path(raw)
        return p if p.is_absolute() else (base_dir / p).resolve()

    return StackSettings(
        name=data["name"],
        group=data["group"],
        version=data.get("version", "v1alpha1"),
        xrd_dir=_resolve(data.get("xrd_dir", ".")),
        output_dir=_resolve(data.get("output_dir", ".")),
        resources=resources,
        wires=wires,
        function_go_templating=data.get(
            "function_go_templating", "function-go-templating"
        ),
        function_auto_ready=data.get("function_auto_ready", "function-auto-ready"),
    )


def _settings_from_flags(
    name: str,
    xrd_dir: Path,
    output_dir: Path,
    group: str,
    version: str,
    resources: list[str],
    wires: list[str],
    function_go_templating: str,
    function_auto_ready: str,
) -> StackSettings:
    """Build StackSettings from CLI flags."""
    if not name:
        raise ValueError("--name is required when not using --file.")
    if not resources:
        raise ValueError("At least one --resource is required.")

    return StackSettings(
        name=name,
        group=group,
        version=version,
        xrd_dir=xrd_dir,
        output_dir=output_dir,
        resources=[_parse_resource_flag(r) for r in resources],
        wires=[_parse_wire_flag(w) for w in wires],
        function_go_templating=function_go_templating,
        function_auto_ready=function_auto_ready,
    )


def run_stack(
    stack_file: Path | None,
    name: str,
    xrd_dir: Path,
    output_dir: Path,
    group: str,
    version: str,
    resources: list[str],
    wires: list[str],
    function_go_templating: str,
    function_auto_ready: str,
) -> None:
    """Generate XRD + Composition for a Stack."""
    if stack_file:
        settings = _settings_from_file(stack_file)
    else:
        settings = _settings_from_flags(
            name=name,
            xrd_dir=xrd_dir,
            output_dir=output_dir,
            group=group,
            version=version,
            resources=resources,
            wires=wires,
            function_go_templating=function_go_templating,
            function_auto_ready=function_auto_ready,
        )

    LOGGER.info(
        "Generating Stack '%s' with %d resources...",
        settings.name,
        len(settings.resources),
    )

    # Load all referenced Infra XRDs
    infra_xrds: dict[str, dict] = {}
    for resource in settings.resources:
        try:
            infra_xrds[resource.name] = load_xrd(settings.xrd_dir, resource.xrd)
            LOGGER.info("  Loaded XRD '%s' → %s", resource.xrd, resource.name)
        except FileNotFoundError as e:
            LOGGER.warning("  %s — proceeding without schema", e)
            infra_xrds[resource.name] = {}

    xrd = generate_stack_xrd(settings, infra_xrds)
    composition = generate_stack_composition(settings, infra_xrds)

    settings.output_dir.mkdir(parents=True, exist_ok=True)
    xrd_path = settings.output_dir / "xrd.yaml"
    comp_path = settings.output_dir / "composition.yaml"

    header = (
        f"# Generated by tf2crossplane stack — {settings.name}\n"
        "# Do not edit manually — re-run tf2crossplane stack to regenerate.\n"
    )

    with open(xrd_path, "w") as f:
        f.write(header)
        yaml.dump(xrd, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    with open(comp_path, "w") as f:
        f.write(header)
        yaml.dump(
            composition,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )

    LOGGER.info("Written: %s", xrd_path)
    LOGGER.info("Written: %s", comp_path)
